// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBew8NiajzM6MYLWj0HTbDHBEEzPoTbLNk',
    appId: '1:1089643255213:web:7b3b249e8b65e7cb86fd24',
    messagingSenderId: '1089643255213',
    projectId: 'amende-a6b18',
    authDomain: 'amende-a6b18.firebaseapp.com',
    storageBucket: 'amende-a6b18.firebasestorage.app',
    measurementId: 'G-XCRLZYNPKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlXyHTHn-0S1pw5RW5J_vGDDqVmeuEGdg',
    appId: '1:1089643255213:android:17460079eee906e186fd24',
    messagingSenderId: '1089643255213',
    projectId: 'amende-a6b18',
    storageBucket: 'amende-a6b18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwivGe8oEhhDxotio1vD7kPmNzJot7UOA',
    appId: '1:1089643255213:ios:5e32f5bf84e4e14786fd24',
    messagingSenderId: '1089643255213',
    projectId: 'amende-a6b18',
    storageBucket: 'amende-a6b18.firebasestorage.app',
    iosBundleId: 'com.example.applicationAmende',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwivGe8oEhhDxotio1vD7kPmNzJot7UOA',
    appId: '1:1089643255213:ios:5e32f5bf84e4e14786fd24',
    messagingSenderId: '1089643255213',
    projectId: 'amende-a6b18',
    storageBucket: 'amende-a6b18.firebasestorage.app',
    iosBundleId: 'com.example.applicationAmende',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBew8NiajzM6MYLWj0HTbDHBEEzPoTbLNk',
    appId: '1:1089643255213:web:d8ef8378d75014b286fd24',
    messagingSenderId: '1089643255213',
    projectId: 'amende-a6b18',
    authDomain: 'amende-a6b18.firebaseapp.com',
    storageBucket: 'amende-a6b18.firebasestorage.app',
    measurementId: 'G-SJZTY8VN8Y',
  );
}
